config/routes.rb
Rails.application.routes.draw do
  root 'areas#index'
  get '/areas/search', to: 'areas#new'
  post '/areas/search', to: 'areas#create' #createアクションのビューでedit.html.erbを呼び出す。
  post '/areas',  to: 'areas#update' #introductionも含めて保存するアクション
  resources :areas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  validates :introduction,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  include Address
  def index
    @area = Area.all
  end

  def new
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    post_api
  end

  def update
    @area = Area.new(area_params)
    if @area.save
      flash[:notice] = '地域を登録しました。'
      redirect_to root_path
    else
      flash.now[:alert] = "Validation failed: #{@area.errors.full_messages.join}"
      render action: :edit
    end
  end

  private

  def area_params
    params.require(:area).permit(:zipcode, :prefcode, :address1, :address2, :address3, :kana1, :kana2, :kana3, :introduction)
  end
end

app/controllers/concerns/address.rb
module Address

  def post_api
    require 'net/http'
    require 'uri'
    require "json"
    main_url = "http://zipcloud.ibsnet.co.jp/api/search?zipcode="
    entry_url = @area.zipcode
    new_url = main_url + entry_url
    begin
      res = Net::HTTP.get(URI.parse(new_url))
      if JSON.parse(res)["status"] == 400
        flash.now[:alert] = JSON.parse(res)["message"]
        @area.zipcode = nil
        render :new
      else
        hash = JSON.parse(res)
        @area.zipcode = hash["results"][0]["zipcode"]
        @area.prefcode = hash["results"][0]["prefcode"]
        @area.address1 = hash["results"][0]["address1"]
        @area.address2 = hash["results"][0]["address2"]
        @area.address3 = hash["results"][0]["address3"]
        @area.kana1 = hash["results"][0]["kana1"]
        @area.kana2 = hash["results"][0]["kana2"]
        @area.kana3 = hash["results"][0]["kana3"]     
        render action: :edit
      end
    rescue => e
      flash.now[:alert] = "パラメーターが不正です。"
      @area.zipcode = nil
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/edit.html.erb
<div class="col-md-6 offset-md-3 mt-4">
  <div class = "form-group">
    <h1>エリア登録</h1>
    <%= form_with url: '/areas', model: @area, local: true do |form| %>
      <%= form.label :zipcode, 'Zipcode' %>
      <%= form.text_field :zipcode, value: @area.zipcode, readonly: true, class: 'form-control mb-3' %>
      <%= form.label :prefcode, 'Prefcode' %>
      <%= form.text_field :prefcode, value: @area.prefcode, readonly: true, class: 'form-control mb-3' %>
      <%= form.label :address1, 'Address1' %>
      <%= form.text_field :address1, value: @area.address1, readonly: true, class: 'form-control mb-3' %>
      <%= form.label :kana1, 'Kana1' %>
      <%= form.text_field :kana1, value: @area.kana1, readonly: true, class: 'form-control mb-3' %>
      <%= form.label :address2, 'Address2' %>
      <%= form.text_field :address2, value: @area.address2, readonly: true, class: 'form-control mb-3' %>
      <%= form.label :kana2, 'Kana2' %>
      <%= form.text_field :kana2, value: @area.kana2, readonly: true, class: 'form-control mb-3' %>
      <%= form.label :address3, 'Address3' %>
      <%= form.text_field :address3, value: @area.address3, readonly: true, class: 'form-control mb-3' %>
      <%= form.label :kana3, 'Kana3' %>
      <%= form.text_field :kana3, value: @area.kana3, readonly: true, class: 'form-control mb-3' %>
      <%= form.label :introduction, 'Introduction' %>
      <%= form.text_area :introduction, value: @area.introduction, class: 'form-control mb-3' %>
      <%= form.submit '登録する', class: "btn btn-primary form-control mt-2"%>
    <% end %>
  </div>
</div>

app/views/areas/index.html.erb
<div class="col-md-12 mt-5">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>ZipCode</th>
        <th>PrefCode</th>
        <th>Address</th>
        <th>Kana</th>
        <th>Introduction</th>
      </tr>
    </thead>
    <tbody>
      <% @area.each do |area| %>
        <tr>
          <th><%= area.id %></th>
          <td><%= area.zipcode %></td>
          <td><%= area.prefcode %></td>
          <td><%= area.address1 %><%= area.address2 %><%= area.address3 %></td>
          <td><%= area.kana1 %><%= area.kana2 %><%= area.kana3 %></td>
          <td><%= area.introduction %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "検索する", areas_search_path, style:"color:white;", class: "btn btn-primary col-12"  %>
</div>

app/views/areas/new.html.erb
<div class="col-md-6 offset-md-3 mt-4">  
  <h1>エリア検索</h1>
  <p><%= form_with url: '/areas/search', model: @area, local: true do |form| %>
    <%= form.label :zipcode, "郵便番号で検索" %>
    <%= form.text_field :zipcode , class: "col-12"%></p>
    <%= form.submit "検索", style:"color:white;", class: "btn btn-primary col-12"  %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampWeekdayTask10</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="..">Areas</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/areas/search">AreaSearch</a>
      </li>
    </ul>
  </div>
  </nav>
  <div class="container">
    <% if flash.notice %>
    <div class="col-md-12 mt-5">
      <div class="alert alert-success" role="alert">
        <%= flash.notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
    <% end %>
    <% if flash.alert %>
    <div class="col-md-6 offset-md-3 mt-5">
      <div class="alert alert-danger" role="alert">
        <%= flash.alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
  </div>
  <% end %>
    <%= yield %>
  </div>
  </body>
</html>